<a href="https://colab.research.google.com/github/chihab216/Implementation-from-scratch-of-svm-and-gradient-descent/blob/master/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import package
import numpy as np
from random import *

In [ ]:
# Initialization
x = np.array([[1,1]])
x = np.transpose(x)

H = np.array([ [7.0, 5.0], [5.0, 7.0] ])
b = np.array([[-3.0, 2.0]])

[[7. 5.]
 [5. 7.]] [[1]
 [1]]


We calculate the optimal solution with an other solver to see if the result of the others methods are good


In [ ]:
# We want to minimize this function f(x) = xt * H * x + bt * x
def f(x,H,b):
  xt = np.transpose(x)
  HX = np.dot(H,x)
  bt = np.transpose(b)
  return(0.5 * np.dot(xt,HX) + np.dot(b,x) )

xopt = np.transpose(np.array([[ 1.29166667, -1.20833333]]))#solution optimal du probleme calculer avec un autre solveur

In [ ]:
def gradF(x,H,b):
  return(np.dot(H,x)+np.transpose(b))

#descente du gradient avec un pas constant(t) et differentes conditions d'arrets
#condition d'arret 1
def optim(x0,H,b,eps,t):
  while np.linalg.norm(gradF(x0,H,b)) > eps:
    deltax = -gradF(x0,H,b)
    x0 = x0 + t*deltax
  return(x0)

#condition d'arret 2
def optim2(x0,H,b,eps,t):
  deltax = -gradF(x0,H,b)
  while np.linalg.norm(t*deltax) > eps :
    deltax = -gradF(x0,H,b)
    x0 = x0 + t*deltax
  return(x0)

#condition d'arret 3
def optim3(x0,H,b,eps,t):
  g=f(x0,H,b)
  deltax = -gradF(x0,H,b)
  x0 = x0 + t*deltax
  while np.linalg.norm(g-f(x0,H,b))>eps:
    g=f(x0,H,b)
    deltax = -gradF(x0,H,b)
    x0 = x0 + t*deltax
  return(x0)

##descente du gradient avec un pas optimal
#calcul du pas par recherche du minimum de f(x0+t*deltax,H,b) par methode itérative 
def optim4(x0,H,b,eps):
  alpha= uniform(0.000000001, 0.4999999999999999)
  beta= uniform(0.000000000001, 1)
  t=1
  n=0
  while np.linalg.norm(gradF(x0,H,b))>eps and n<100000:
    deltax = -gradF(x0,H,b)
    while f(x0+t*deltax,H,b)[0][0] > (f(x0,H,b)+ alpha*t*np.dot(np.transpose(gradF(x0,H,b)),deltax))[0][0]:
      t=beta*t
    x0 = x0 + t*deltax
    n=n+1
  return(x0)

#calcul du pas par recherche du minimum de f(x0+t*deltax,H,b) par methode exacte
def optim5(x0,H,b,eps):
  while np.linalg.norm(gradF(x0,H,b))>eps  :
    deltax = -gradF(x0,H,b)
    HD=np.dot(H,deltax)
    deltaxt=np.transpose(deltax)
    t=abs((np.dot(np.transpose(gradF(x0,H,b)),deltax))[0][0]/(np.dot(deltaxt,HD))[0][0]) 
    x0 = x0 + t*deltax 
  return(x0)

##descente du gradient avec un sens de descente calculer par la methode de newton
def optim6(x0,H,b,eps):
  while np.linalg.norm(gradF(x0,H,b))>eps  :
    deltax =-np.dot(np.linalg.inv(H),gradF(x0,H,b))
    HD=np.dot(H,deltax)
    deltaxt=np.transpose(deltax)
    t=abs((np.dot(np.transpose(gradF(x0,H,b)),deltax))[0][0]/(np.dot(deltaxt,HD))[0][0]) 
    x0 = x0 + t*deltax 
  return(x0)

##descente du gradient avec un sens de descente calculer par la methode stochastique mais ne coverge pas
def optim7(x0,H,b,eps):
  n = H.shape[1]
  deltax= np.random.rand(n,1)
  p=0
  while np.linalg.norm(gradF(x0,H,b)) > eps and p<10000 :
    if np.vdot(gradF(x0,H,b),deltax)>0:
      deltax=-deltax
    if np.vdot(gradF(x0,H,b),deltax)<0:
       deltax=deltax
    if np.vdot(gradF(x0,H,b),deltax)==0:
      deltax= np.random.rand(n,1)
    HD=np.dot(H,deltax)
    deltaxt=np.transpose(deltax)
    t=abs((np.dot(np.transpose(gradF(x0,H,b)),deltax))[0][0]/(np.dot(deltaxt,HD))[0][0]) 
    x0 = x0 + t*deltax 
    p=p+1
  return(x0)



In [ ]:
print("Résultats avec un pas constant alpha =0.01 : ")
print("condition d'arret 1 :norme du gradient inférieur à un epsilone de l'ordre de 10E-8")
print(optim(x,H,b,0.00000001,0.01))
print("condition d'arret 2 :norme de xk+1 - xk inférieur à un epsilone de l'ordre de 10E-8")
print(optim2(x,H,b,0.00000001,0.01))
print("condition d'arret 3 :norme de f(xk+1) - f(xk) inférieur à un epsilone de l'ordre de 10E-8")
print(optim3(x,H,b,0.00000001,0.01))

print("\n")

print("Résultats avec un pas optimal ")
print("calcul du pas par recherche du minimum de f(x0+t*deltax,H,b) par methode itérative ")
print(optim4(x,H,b,0.00000001))
print("calcul du pas par recherche du minimum de f(x0+t*deltax,H,b) par methode exacte")
print(optim5(x,H,b,0.00000001))

print("\n")

print("descente du gradient avec un sens de descente calculer par la methode de newton")
print(optim6(x,H,b,0.00000001))
print("descente stochastique mais ne donne pas un bon resultat")
print(optim7(x,H,b,0.00000001))

Résultats avec un pas constant alpha =0.01 : 
condition d'arret 1 :norme du gradient inférieur à un epsilone de l'ordre de 10E-8
[[ 1.29166666]
 [-1.20833333]]
condition d'arret 2 :norme de xk+1 - xk inférieur à un epsilone de l'ordre de 10E-8
[[ 1.29166632]
 [-1.20833299]]
condition d'arret 3 :norme de f(xk+1) - f(xk) inférieur à un epsilone de l'ordre de 10E-8
[[ 1.29132414]
 [-1.2079908 ]]


Résultats avec un pas optimal 
calcul du pas par recherche du minimum de f(x0+t*deltax,H,b) par methode itérative 
[[ 1.29166661]
 [-1.20833327]]
calcul du pas par recherche du minimum de f(x0+t*deltax,H,b) par methode exacte
[[ 1.29166667]
 [-1.20833333]]


descente du gradient avec un sens de descente calculer par la methode de newton
[[ 1.29166667]
 [-1.20833333]]
descente stochastique mais ne donne pas un bon resultat
[[0.15775658]
 [0.27456726]]
